(* Generated by ocaml-rs *)

open! Bigarray

(* file: stubs.rs *)

type promise
type executor
external lwti_executor_create: int -> executor = "lwti_executor_create"
external lwti_executor_run_pending: executor -> unit = "lwti_executor_run_pending"
external lwti_executor_bench: executor -> unit Lwt.t = "lwti_executor_bench"
external lwti_executor_test: executor -> unit Lwt.t = "lwti_executor_test"
