name: Rust tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
        ocaml-compiler:
          [
            "4.14.1",
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: OCaml/Opam cache
        id: ocaml-rs-opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: ocaml-rs-opam-${{ matrix.ocaml-compiler }}-${{ matrix.os }}

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Set Opam env
        run: opam env | tr '\n' ' ' >> $GITHUB_ENV

      - name: Add Opam switch to PATH
        run: opam var bin >> $GITHUB_PATH

      - name: Build
        run: cargo build --verbose
